<a href="https://colab.research.google.com/github/Vukki09/cloud_repo/blob/master/Numpy_solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
#b
b=np.zeros(10)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
#c
d=np.ones(10)
print(d)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [11]:
#d
t=np.ones(10)*5
print(t)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [7]:
#e
q=np.arange(10,50)
print(q)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
#f
w=np.arange(10,50,2)
print(w)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [39]:
#g Создать матрицу 3х3 с числами от 0 до 8
s=np.linspace(0,8,9)
p=s.reshape(3, 3)
print(p)



[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [19]:
#h Создать единичную матрицу 3x3
l=np.eye(3)
print(l)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
#i Используйте NumPy для генерации случайного числа от 0 до 1
m=np.random.rand()
print(m)


0.7067726901647046


In [26]:
#j Используйте NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения
z=np.random.randn(25)
print(z)

[ 1.04571869 -1.90457539  0.74490202  0.00924838 -0.87215687 -0.48760245
 -1.2153268   0.12841947  0.509773    0.68846968 -1.43842772  0.51086727
 -0.48896594 -0.11818018 -2.51049151  0.42503245 -0.38061986  3.46194027
 -0.60583365 -0.53885876 -0.84041814 -0.07063665 -0.35382325 -0.4790658
 -0.38118295]


In [45]:
#k Создайте следующую матрицу используя функции библиотеки NumPy
s=np.linspace(0.01,1,100)
print(s.reshape(10,10))

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [3]:
#l
mat = np.arange(1,26).reshape(5,5)
print([mat])


[array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])]


In [105]:
y=mat[2:, [1,2,3,4]]
print([y])

[array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])]


In [91]:
#m Написать код обращения к элементу который вернет значение  20 изстартовой матрицы задачи l
print(mat[3][4])


20


In [9]:
#n
y=mat[0:3, [1]]
print([y])

[array([[ 2],
       [ 7],
       [12]])]


In [10]:
#o
y=mat[4:]
print([y])

[array([[21, 22, 23, 24, 25]])]


In [11]:
#p
y=mat[3:]
print([y])

[array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])]


In [12]:
#q
print(mat.sum())

325


In [15]:
#r
print(mat.std())


7.211102550927978


In [13]:
#s
print(mat.sum(axis=0))

[55 60 65 70 75]
